name: cs294w
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_15
  - libgcc-ng=15.2.0=h69a702a_15
  - libgomp=15.2.0=he0feb66_15
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.1=h0c1763c_0
  - libuuid=2.41.2=h5347b49_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.12.12=hd63d673_1_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - accelerate==1.12.0
      - adpbulk==0.1.4
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anndata==0.12.7
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      #- arc-state==0.9.33 # this is from a local install
      - array-api-compat==1.12.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - cell-eval==0.6.6
      - cell-load==0.8.6
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.4.1
      - debugpy==1.8.19
      - decorator==5.2.1
      - dill==0.4.0
      - donfig==0.8.1.post1
      - executing==2.2.1
      - filelock==3.20.1
      - fonttools==4.61.1
      - formulaic==1.2.1
      - formulaic-contrasts==1.0.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - geomloss==0.2.6
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-crc32c==1.8.0
      - gprofiler-official==1.0.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - idna==3.11
      - igraph==1.0.0
      - iniconfig==2.3.0
      - inquirerpy==0.3.4
      - interface-meta==1.3.0
      - ipykernel==7.1.0
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - legacy-api-wrap==1.5
      - lightning==2.6.0
      - lightning-utilities==0.15.2
      - llvmlite==0.46.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - narwhals==2.14.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - numba==0.63.1
      - numcodecs==0.16.5
      - numpy==2.3.5
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - pandas==2.3.3
      - parso==0.8.5
      - patsy==1.0.2
      - pdex==0.1.27
      - peft==0.18.0
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==12.0.0
      - pluggy==1.6.0
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pubchempy==1.0.5
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydeseq2==0.5.3
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scanpy==1.11.5
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - sentry-sdk==2.48.0
      - session-info==1.0.1
      - session-info2==0.2.3
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - statsmodels==0.14.6
      - stdlib-list==0.12.0
      - sympy==1.14.0
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - torch==2.9.1
      - torchmetrics==1.8.2
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - triton==3.5.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - umap-learn==0.5.9.post2
      - urllib3==2.6.2
      - wandb==0.23.1
      - wcwidth==0.2.14
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zarr==3.1.5
prefix: /home/qile/miniconda3/envs/cs294w
